(() => {
  const TAGLINES = [
    "crush it",
    "grind harder",
    "push limits",
    "get stronger",
    "stay consistent",
    "break records",
    "level up",
    "go hard",
  ];

  const DEFAULT_WORKOUTS = [
    {
      id: "d1",
      name: "Push Day A",
      icon: "💪",
      description: "Chest · Shoulders · Triceps",
      exercises: [
        { name: "Bench Press", icon: "🏋️", sets: 4, reps: 8, rest: 120, weight: 60 },
        { name: "Incline DB Press", icon: "💪", sets: 4, reps: 12, rest: 75, weight: 24 },
        { name: "Cable Fly", icon: "🔄", sets: 3, reps: 15, rest: 60, weight: 15 },
        { name: "Shoulder Press", icon: "🏋️", sets: 4, reps: 10, rest: 90, weight: 40 },
        { name: "Lateral Raise", icon: "🦾", sets: 3, reps: 15, rest: 45, weight: 10 },
        { name: "Tricep Dips", icon: "💥", sets: 3, reps: 12, rest: 60, weight: 0 },
      ],
    },
    {
      id: "d2",
      name: "Pull Day B",
      icon: "🤸",
      description: "Back · Biceps · Rear Delts",
      exercises: [
        { name: "Pull-ups", icon: "🤸", sets: 4, reps: 8, rest: 90, weight: 0 },
        { name: "Barbell Row", icon: "🏋️", sets: 4, reps: 10, rest: 90, weight: 60 },
        { name: "Lat Pulldown", icon: "🔄", sets: 3, reps: 12, rest: 75, weight: 50 },
        { name: "Face Pull", icon: "🔄", sets: 3, reps: 15, rest: 60, weight: 15 },
        { name: "Hammer Curl", icon: "💪", sets: 3, reps: 12, rest: 60, weight: 16 },
      ],
    },
    {
      id: "d3",
      name: "Leg Day",
      icon: "🦵",
      description: "Quads · Glutes · Hamstrings",
      exercises: [
        { name: "Barbell Squat", icon: "🦵", sets: 5, reps: 8, rest: 120, weight: 80 },
        { name: "Romanian Deadlift", icon: "🏋️", sets: 4, reps: 10, rest: 90, weight: 70 },
        { name: "Leg Press", icon: "💺", sets: 4, reps: 12, rest: 75, weight: 100 },
        { name: "Walking Lunge", icon: "🦵", sets: 3, reps: 20, rest: 60, weight: 20 },
        { name: "Calf Raise", icon: "⬆️", sets: 4, reps: 20, rest: 45, weight: 40 },
      ],
    },
    {
      id: "d4",
      name: "HIIT Cardio",
      icon: "🔥",
      description: "Fat Burn · No Equipment",
      exercises: [
        { name: "Burpees", icon: "🔥", sets: 4, reps: 15, rest: 30, weight: 0 },
        { name: "Jump Squats", icon: "⚡", sets: 4, reps: 20, rest: 30, weight: 0 },
        { name: "Mountain Climbers", icon: "🏔️", sets: 3, reps: 30, rest: 30, weight: 0 },
        { name: "High Knees", icon: "🦵", sets: 3, reps: 40, rest: 30, weight: 0 },
      ],
    },
    {
      id: "d5",
      name: "Push-Up Power",
      icon: "🤸",
      description: "Bodyweight · No Equipment",
      exercises: [
        { name: "Push-Ups", icon: "🤸", sets: 4, reps: 20, rest: 60, weight: 0 },
        { name: "Wide Push-Ups", icon: "🤸", sets: 3, reps: 15, rest: 60, weight: 0 },
        { name: "Diamond Push-Ups", icon: "💎", sets: 3, reps: 12, rest: 75, weight: 0 },
        { name: "Pike Push-Ups", icon: "⬆️", sets: 3, reps: 10, rest: 75, weight: 0 },
      ],
    },
  ];

  const EXERCISE_LIBRARY = [
    {
      label: "Bodyweight",
      exercises: [
        "Push-ups",
        "Wide Push-ups",
        "Diamond Push-ups",
        "Pike Push-ups",
        "Pull-ups",
        "Chin-ups",
        "Dips",
        "Inverted Rows",
        "Bodyweight Squats",
        "Jump Squats",
        "Walking Lunges",
        "Bulgarian Split Squats",
        "Glute Bridges",
        "Burpees",
        "Mountain Climbers",
        "High Knees",
        "Plank",
        "Side Plank",
        "Hollow Hold",
        "Russian Twists",
        "Leg Raises",
        "Sit-ups",
        "Crunches",
      ],
    },
    {
      label: "Machines",
      exercises: [
        "Leg Press",
        "Leg Extension",
        "Seated Leg Curl",
        "Lying Leg Curl",
        "Calf Raise Machine",
        "Chest Press Machine",
        "Incline Chest Press Machine",
        "Pec Deck",
        "Cable Fly",
        "Lat Pulldown",
        "Seated Cable Row",
        "Assisted Pull-up Machine",
        "Assisted Dip Machine",
        "Smith Machine Squat",
        "Smith Machine Bench Press",
        "Hack Squat",
        "Hip Abductor Machine",
        "Hip Adductor Machine",
        "Glute Drive Machine",
        "Shoulder Press Machine",
        "Cable Lateral Raise",
        "Triceps Pushdown",
        "Cable Curl",
        "Ab Crunch Machine",
      ],
    },
    {
      label: "Free Weights",
      exercises: [
        "Bench Press",
        "Incline DB Press",
        "Shoulder Press",
        "Overhead Press",
        "Arnold Press",
        "Barbell Row",
        "Romanian Deadlift",
        "Deadlift",
        "Barbell Squat",
        "Goblet Squat",
        "Hip Thrust",
        "Dumbbell Fly",
        "Lateral Raise",
        "Face Pull",
        "Hammer Curl",
        "Bicep Curl",
        "Tricep Extension",
        "Skull Crusher",
        "Close Grip Bench",
        "Upright Row",
      ],
    },
    {
      label: "Core & Cardio",
      exercises: [
        "Cable Crunch",
        "Ab Wheel Rollout",
        "Hanging Knee Raise",
        "Flutter Kicks",
        "Jump Rope",
        "Rowing Machine",
        "Bike Sprint",
        "Treadmill Run",
        "Stair Climber",
        "Elliptical Intervals",
      ],
    },
  ];

  const CATEGORY_DEFAULTS = {
    Bodyweight: { icon: "🤸", sets: 3, reps: 12, rest: 60, weight: 0 },
    Machines: { icon: "🏋️", sets: 3, reps: 12, rest: 75, weight: 0 },
    "Free Weights": { icon: "💪", sets: 4, reps: 10, rest: 90, weight: 0 },
    "Core & Cardio": { icon: "🔥", sets: 3, reps: 15, rest: 45, weight: 0 },
  };

  const EXERCISE_OVERRIDES = {
    "Push-ups": { icon: "🤸", sets: 4, reps: 15, rest: 60 },
    "Wide Push-ups": { icon: "🤸", sets: 3, reps: 12, rest: 60 },
    "Diamond Push-ups": { icon: "💎", sets: 3, reps: 10, rest: 75 },
    "Pike Push-ups": { icon: "⬆️", sets: 3, reps: 10, rest: 75 },
    "Pull-ups": { icon: "🤸", sets: 4, reps: 8, rest: 90 },
    "Chin-ups": { icon: "🤸", sets: 4, reps: 8, rest: 90 },
    "Dips": { icon: "💥", sets: 4, reps: 10, rest: 75 },
    "Burpees": { icon: "🔥", sets: 4, reps: 15, rest: 30 },
    "Mountain Climbers": { icon: "🏔️", sets: 3, reps: 30, rest: 30 },
    "High Knees": { icon: "🦵", sets: 3, reps: 40, rest: 30 },
    "Plank": { icon: "🧱", sets: 3, reps: 1, rest: 45 },
    "Side Plank": { icon: "🧱", sets: 3, reps: 1, rest: 45 },
    "Bench Press": { icon: "🏋️", sets: 4, reps: 8, rest: 120 },
    "Incline DB Press": { icon: "💪", sets: 4, reps: 10, rest: 90 },
    "Shoulder Press": { icon: "🏋️", sets: 4, reps: 10, rest: 90 },
    "Overhead Press": { icon: "🏋️", sets: 4, reps: 8, rest: 120 },
    "Barbell Row": { icon: "🏋️", sets: 4, reps: 10, rest: 90 },
    "Romanian Deadlift": { icon: "🏋️", sets: 4, reps: 10, rest: 90 },
    "Deadlift": { icon: "🏋️", sets: 5, reps: 5, rest: 150 },
    "Barbell Squat": { icon: "🦵", sets: 5, reps: 8, rest: 120 },
    "Goblet Squat": { icon: "🦵", sets: 4, reps: 12, rest: 75 },
    "Hip Thrust": { icon: "🍑", sets: 4, reps: 10, rest: 90 },
    "Lateral Raise": { icon: "🦾", sets: 3, reps: 15, rest: 45 },
    "Face Pull": { icon: "🔄", sets: 3, reps: 15, rest: 60 },
    "Hammer Curl": { icon: "💪", sets: 3, reps: 12, rest: 60 },
    "Bicep Curl": { icon: "💪", sets: 3, reps: 12, rest: 60 },
    "Tricep Extension": { icon: "💥", sets: 3, reps: 12, rest: 60 },
    "Skull Crusher": { icon: "💥", sets: 3, reps: 10, rest: 75 },
    "Leg Press": { icon: "🦵", sets: 4, reps: 12, rest: 75 },
    "Leg Extension": { icon: "🦵", sets: 3, reps: 15, rest: 60 },
    "Seated Leg Curl": { icon: "🦵", sets: 3, reps: 15, rest: 60 },
    "Lying Leg Curl": { icon: "🦵", sets: 3, reps: 15, rest: 60 },
    "Calf Raise Machine": { icon: "⬆️", sets: 4, reps: 18, rest: 45 },
    "Chest Press Machine": { icon: "🏋️", sets: 4, reps: 10, rest: 75 },
    "Incline Chest Press Machine": { icon: "🏋️", sets: 4, reps: 10, rest: 75 },
    "Pec Deck": { icon: "🔄", sets: 3, reps: 15, rest: 60 },
    "Cable Fly": { icon: "🔄", sets: 3, reps: 15, rest: 60 },
    "Lat Pulldown": { icon: "🔄", sets: 4, reps: 12, rest: 75 },
    "Seated Cable Row": { icon: "🔄", sets: 4, reps: 12, rest: 75 },
    "Assisted Pull-up Machine": { icon: "🤸", sets: 4, reps: 10, rest: 75 },
    "Assisted Dip Machine": { icon: "💥", sets: 4, reps: 10, rest: 75 },
    "Smith Machine Squat": { icon: "🦵", sets: 4, reps: 10, rest: 90 },
    "Smith Machine Bench Press": { icon: "🏋️", sets: 4, reps: 8, rest: 90 },
    "Hack Squat": { icon: "🦵", sets: 4, reps: 10, rest: 90 },
    "Hip Abductor Machine": { icon: "🦵", sets: 3, reps: 15, rest: 60 },
    "Hip Adductor Machine": { icon: "🦵", sets: 3, reps: 15, rest: 60 },
    "Glute Drive Machine": { icon: "🍑", sets: 4, reps: 12, rest: 75 },
    "Shoulder Press Machine": { icon: "🏋️", sets: 4, reps: 10, rest: 75 },
    "Cable Lateral Raise": { icon: "🦾", sets: 3, reps: 15, rest: 45 },
    "Triceps Pushdown": { icon: "💥", sets: 3, reps: 12, rest: 60 },
    "Cable Curl": { icon: "💪", sets: 3, reps: 12, rest: 60 },
    "Ab Crunch Machine": { icon: "🔥", sets: 3, reps: 15, rest: 45 },
    "Cable Crunch": { icon: "🔥", sets: 3, reps: 15, rest: 45 },
    "Ab Wheel Rollout": { icon: "🔥", sets: 3, reps: 12, rest: 45 },
    "Hanging Knee Raise": { icon: "🔥", sets: 3, reps: 15, rest: 45 },
    "Flutter Kicks": { icon: "🔥", sets: 3, reps: 25, rest: 30 },
    "Jump Rope": { icon: "⚡", sets: 5, reps: 60, rest: 30 },
    "Rowing Machine": { icon: "🚣", sets: 4, reps: 500, rest: 45 },
    "Bike Sprint": { icon: "🚴", sets: 8, reps: 30, rest: 30 },
    "Treadmill Run": { icon: "🏃", sets: 1, reps: 20, rest: 0 },
    "Stair Climber": { icon: "🪜", sets: 1, reps: 15, rest: 0 },
    "Elliptical Intervals": { icon: "⚡", sets: 6, reps: 60, rest: 30 },
  };

  const MUSCLE_DEFAULTS = {
    Bodyweight: "Full Body",
    Machines: "Strength",
    "Free Weights": "Strength",
    "Core & Cardio": "Core",
  };

  const EXERCISE_MUSCLE_OVERRIDES = {
    "Push-ups": "Chest",
    "Wide Push-ups": "Chest",
    "Diamond Push-ups": "Arms",
    "Pike Push-ups": "Shoulders",
    "Pull-ups": "Back",
    "Chin-ups": "Back",
    "Dips": "Chest",
    "Inverted Rows": "Back",
    "Bodyweight Squats": "Legs",
    "Jump Squats": "Legs",
    "Walking Lunges": "Legs",
    "Bulgarian Split Squats": "Legs",
    "Glute Bridges": "Legs",
    "Burpees": "Cardio",
    "Mountain Climbers": "Cardio",
    "High Knees": "Cardio",
    "Plank": "Core",
    "Side Plank": "Core",
    "Hollow Hold": "Core",
    "Russian Twists": "Core",
    "Leg Raises": "Core",
    "Sit-ups": "Core",
    "Crunches": "Core",
    "Leg Press": "Legs",
    "Leg Extension": "Legs",
    "Seated Leg Curl": "Legs",
    "Lying Leg Curl": "Legs",
    "Calf Raise Machine": "Legs",
    "Chest Press Machine": "Chest",
    "Incline Chest Press Machine": "Chest",
    "Pec Deck": "Chest",
    "Cable Fly": "Chest",
    "Lat Pulldown": "Back",
    "Seated Cable Row": "Back",
    "Assisted Pull-up Machine": "Back",
    "Assisted Dip Machine": "Chest",
    "Smith Machine Squat": "Legs",
    "Smith Machine Bench Press": "Chest",
    "Hack Squat": "Legs",
    "Hip Abductor Machine": "Legs",
    "Hip Adductor Machine": "Legs",
    "Glute Drive Machine": "Legs",
    "Shoulder Press Machine": "Shoulders",
    "Cable Lateral Raise": "Shoulders",
    "Triceps Pushdown": "Arms",
    "Cable Curl": "Arms",
    "Ab Crunch Machine": "Core",
    "Bench Press": "Chest",
    "Incline DB Press": "Chest",
    "Shoulder Press": "Shoulders",
    "Overhead Press": "Shoulders",
    "Arnold Press": "Shoulders",
    "Barbell Row": "Back",
    "Romanian Deadlift": "Legs",
    "Deadlift": "Legs",
    "Barbell Squat": "Legs",
    "Goblet Squat": "Legs",
    "Hip Thrust": "Legs",
    "Dumbbell Fly": "Chest",
    "Lateral Raise": "Shoulders",
    "Face Pull": "Shoulders",
    "Hammer Curl": "Arms",
    "Bicep Curl": "Arms",
    "Tricep Extension": "Arms",
    "Skull Crusher": "Arms",
    "Close Grip Bench": "Arms",
    "Upright Row": "Shoulders",
    "Cable Crunch": "Core",
    "Ab Wheel Rollout": "Core",
    "Hanging Knee Raise": "Core",
    "Flutter Kicks": "Core",
    "Jump Rope": "Cardio",
    "Rowing Machine": "Cardio",
    "Bike Sprint": "Cardio",
    "Treadmill Run": "Cardio",
    "Stair Climber": "Cardio",
    "Elliptical Intervals": "Cardio",
  };

  const EXERCISE_LOOKUP = Object.freeze(
    EXERCISE_LIBRARY.reduce((lookup, group) => {
      group.exercises.forEach((name) => {
        lookup[name] = {
          name,
          category: group.label,
          muscle: EXERCISE_MUSCLE_OVERRIDES[name] || MUSCLE_DEFAULTS[group.label],
          ...CATEGORY_DEFAULTS[group.label],
          ...(EXERCISE_OVERRIDES[name] || {}),
        };
      });
      return lookup;
    }, {})
  );

  const EXERCISE_PACKS = [
    {
      id: "starter_strength",
      title: "Starter Strength",
      desc: "Balanced full-body strength foundation",
      icon: "💪",
      level: "beginner",
      equipment: ["mixed", "free"],
      workout: {
        name: "Starter Strength",
        description: "Full body · strength basics",
        exercises: ["Goblet Squat", "Bench Press", "Seated Cable Row", "Plank"],
      },
    },
    {
      id: "bodyweight_foundation",
      title: "Bodyweight Base",
      desc: "Simple no-gym full-body plan",
      icon: "🤸",
      level: "beginner",
      equipment: ["bodyweight", "mixed"],
      workout: {
        name: "Bodyweight Base",
        description: "No equipment · full body",
        exercises: ["Push-ups", "Bodyweight Squats", "Inverted Rows", "Mountain Climbers"],
      },
    },
    {
      id: "machine_upper",
      title: "Machine Upper",
      desc: "Chest, back, shoulders with machines",
      icon: "🏋️",
      level: "intermediate",
      equipment: ["machines", "mixed"],
      workout: {
        name: "Machine Upper",
        description: "Machines · upper body",
        exercises: ["Chest Press Machine", "Lat Pulldown", "Seated Cable Row", "Shoulder Press Machine", "Triceps Pushdown"],
      },
    },
    {
      id: "lower_power",
      title: "Lower Power",
      desc: "Leg-focused strength and volume",
      icon: "🦵",
      level: "intermediate",
      equipment: ["free", "machines", "mixed"],
      workout: {
        name: "Lower Power",
        description: "Legs · glutes · hamstrings",
        exercises: ["Barbell Squat", "Romanian Deadlift", "Leg Press", "Calf Raise Machine"],
      },
    },
    {
      id: "push_pull_performance",
      title: "Push Pull Performance",
      desc: "Higher-output upper split for experienced lifters",
      icon: "⚡",
      level: "advanced",
      equipment: ["free", "mixed"],
      workout: {
        name: "Push Pull Performance",
        description: "Upper body · performance",
        exercises: ["Bench Press", "Pull-ups", "Overhead Press", "Barbell Row", "Hammer Curl", "Skull Crusher"],
      },
    },
  ];

  const EXERCISE_POOL = Array.from(
    new Set(EXERCISE_LIBRARY.flatMap((group) => group.exercises))
  );

  window.FITOPRO_DATA = Object.freeze({
    TAGLINES,
    DEFAULT_WORKOUTS,
    EXERCISE_LIBRARY,
    EXERCISE_LOOKUP,
    EXERCISE_PACKS,
    EXERCISE_POOL,
  });
})();
