(() => {
  const TAGLINES = [
    "crush it",
    "grind harder",
    "push limits",
    "get stronger",
    "stay consistent",
    "break records",
    "level up",
    "go hard",
  ];

  const DEFAULT_WORKOUTS = [
    {
      id: "d1",
      name: "Push Day A",
      icon: "💪",
      description: "Chest · Shoulders · Triceps",
      exercises: [
        { name: "Bench Press", icon: "🏋️", sets: 4, reps: 8, rest: 120, weight: 60 },
        { name: "Incline DB Press", icon: "💪", sets: 4, reps: 12, rest: 75, weight: 24 },
        { name: "Cable Fly", icon: "🔄", sets: 3, reps: 15, rest: 60, weight: 15 },
        { name: "Shoulder Press", icon: "🏋️", sets: 4, reps: 10, rest: 90, weight: 40 },
        { name: "Lateral Raise", icon: "🦾", sets: 3, reps: 15, rest: 45, weight: 10 },
        { name: "Tricep Dips", icon: "💥", sets: 3, reps: 12, rest: 60, weight: 0 },
      ],
    },
    {
      id: "d2",
      name: "Pull Day B",
      icon: "🤸",
      description: "Back · Biceps · Rear Delts",
      exercises: [
        { name: "Pull-ups", icon: "🤸", sets: 4, reps: 8, rest: 90, weight: 0 },
        { name: "Barbell Row", icon: "🏋️", sets: 4, reps: 10, rest: 90, weight: 60 },
        { name: "Lat Pulldown", icon: "🔄", sets: 3, reps: 12, rest: 75, weight: 50 },
        { name: "Face Pull", icon: "🔄", sets: 3, reps: 15, rest: 60, weight: 15 },
        { name: "Hammer Curl", icon: "💪", sets: 3, reps: 12, rest: 60, weight: 16 },
      ],
    },
    {
      id: "d3",
      name: "Leg Day",
      icon: "🦵",
      description: "Quads · Glutes · Hamstrings",
      exercises: [
        { name: "Barbell Squat", icon: "🦵", sets: 5, reps: 8, rest: 120, weight: 80 },
        { name: "Romanian Deadlift", icon: "🏋️", sets: 4, reps: 10, rest: 90, weight: 70 },
        { name: "Leg Press", icon: "💺", sets: 4, reps: 12, rest: 75, weight: 100 },
        { name: "Walking Lunge", icon: "🦵", sets: 3, reps: 20, rest: 60, weight: 20 },
        { name: "Calf Raise", icon: "⬆️", sets: 4, reps: 20, rest: 45, weight: 40 },
      ],
    },
    {
      id: "d4",
      name: "HIIT Cardio",
      icon: "🔥",
      description: "Fat Burn · No Equipment",
      exercises: [
        { name: "Burpees", icon: "🔥", sets: 4, reps: 15, rest: 30, weight: 0 },
        { name: "Jump Squats", icon: "⚡", sets: 4, reps: 20, rest: 30, weight: 0 },
        { name: "Mountain Climbers", icon: "🏔️", sets: 3, reps: 30, rest: 30, weight: 0 },
        { name: "High Knees", icon: "🦵", sets: 3, reps: 40, rest: 30, weight: 0 },
      ],
    },
    {
      id: "d5",
      name: "Push-Up Power",
      icon: "🤸",
      description: "Bodyweight · No Equipment",
      exercises: [
        { name: "Push-Ups", icon: "🤸", sets: 4, reps: 20, rest: 60, weight: 0 },
        { name: "Wide Push-Ups", icon: "🤸", sets: 3, reps: 15, rest: 60, weight: 0 },
        { name: "Diamond Push-Ups", icon: "💎", sets: 3, reps: 12, rest: 75, weight: 0 },
        { name: "Pike Push-Ups", icon: "⬆️", sets: 3, reps: 10, rest: 75, weight: 0 },
      ],
    },
  ];

  const EXERCISE_LIBRARY = [
    {
      label: "Bodyweight",
      exercises: [
        "Push-ups",
        "Wide Push-ups",
        "Diamond Push-ups",
        "Pike Push-ups",
        "Pull-ups",
        "Chin-ups",
        "Dips",
        "Inverted Rows",
        "Bodyweight Squats",
        "Jump Squats",
        "Walking Lunges",
        "Bulgarian Split Squats",
        "Glute Bridges",
        "Burpees",
        "Mountain Climbers",
        "High Knees",
        "Plank",
        "Side Plank",
        "Hollow Hold",
        "Russian Twists",
        "Leg Raises",
        "Sit-ups",
        "Crunches",
      ],
    },
    {
      label: "Machines",
      exercises: [
        "Leg Press",
        "Leg Extension",
        "Seated Leg Curl",
        "Lying Leg Curl",
        "Calf Raise Machine",
        "Chest Press Machine",
        "Incline Chest Press Machine",
        "Pec Deck",
        "Cable Fly",
        "Lat Pulldown",
        "Seated Cable Row",
        "Assisted Pull-up Machine",
        "Assisted Dip Machine",
        "Smith Machine Squat",
        "Smith Machine Bench Press",
        "Hack Squat",
        "Hip Abductor Machine",
        "Hip Adductor Machine",
        "Glute Drive Machine",
        "Shoulder Press Machine",
        "Cable Lateral Raise",
        "Triceps Pushdown",
        "Cable Curl",
        "Ab Crunch Machine",
      ],
    },
    {
      label: "Free Weights",
      exercises: [
        "Bench Press",
        "Incline DB Press",
        "Shoulder Press",
        "Overhead Press",
        "Arnold Press",
        "Barbell Row",
        "Romanian Deadlift",
        "Deadlift",
        "Barbell Squat",
        "Goblet Squat",
        "Hip Thrust",
        "Dumbbell Fly",
        "Lateral Raise",
        "Face Pull",
        "Hammer Curl",
        "Bicep Curl",
        "Tricep Extension",
        "Skull Crusher",
        "Close Grip Bench",
        "Upright Row",
      ],
    },
    {
      label: "Core & Cardio",
      exercises: [
        "Cable Crunch",
        "Ab Wheel Rollout",
        "Hanging Knee Raise",
        "Flutter Kicks",
        "Jump Rope",
        "Rowing Machine",
        "Bike Sprint",
        "Treadmill Run",
        "Stair Climber",
        "Elliptical Intervals",
      ],
    },
  ];

  const CATEGORY_DEFAULTS = {
    Bodyweight: { icon: "🤸", sets: 3, reps: 12, rest: 60, weight: 0 },
    Machines: { icon: "🏋️", sets: 3, reps: 12, rest: 75, weight: 0 },
    "Free Weights": { icon: "💪", sets: 4, reps: 10, rest: 90, weight: 0 },
    "Core & Cardio": { icon: "🔥", sets: 3, reps: 15, rest: 45, weight: 0 },
  };

  const EXERCISE_OVERRIDES = {
    "Push-ups": { icon: "🤸", sets: 4, reps: 15, rest: 60 },
    "Wide Push-ups": { icon: "🤸", sets: 3, reps: 12, rest: 60 },
    "Diamond Push-ups": { icon: "💎", sets: 3, reps: 10, rest: 75 },
    "Pike Push-ups": { icon: "⬆️", sets: 3, reps: 10, rest: 75 },
    "Pull-ups": { icon: "🤸", sets: 4, reps: 8, rest: 90 },
    "Chin-ups": { icon: "🤸", sets: 4, reps: 8, rest: 90 },
    "Dips": { icon: "💥", sets: 4, reps: 10, rest: 75 },
    "Burpees": { icon: "🔥", sets: 4, reps: 15, rest: 30 },
    "Mountain Climbers": { icon: "🏔️", sets: 3, reps: 30, rest: 30 },
    "High Knees": { icon: "🦵", sets: 3, reps: 40, rest: 30 },
    "Plank": { icon: "🧱", sets: 3, reps: 1, rest: 45 },
    "Side Plank": { icon: "🧱", sets: 3, reps: 1, rest: 45 },
    "Bench Press": { icon: "🏋️", sets: 4, reps: 8, rest: 120 },
    "Incline DB Press": { icon: "💪", sets: 4, reps: 10, rest: 90 },
    "Shoulder Press": { icon: "🏋️", sets: 4, reps: 10, rest: 90 },
    "Overhead Press": { icon: "🏋️", sets: 4, reps: 8, rest: 120 },
    "Barbell Row": { icon: "🏋️", sets: 4, reps: 10, rest: 90 },
    "Romanian Deadlift": { icon: "🏋️", sets: 4, reps: 10, rest: 90 },
    "Deadlift": { icon: "🏋️", sets: 5, reps: 5, rest: 150 },
    "Barbell Squat": { icon: "🦵", sets: 5, reps: 8, rest: 120 },
    "Goblet Squat": { icon: "🦵", sets: 4, reps: 12, rest: 75 },
    "Hip Thrust": { icon: "🍑", sets: 4, reps: 10, rest: 90 },
    "Lateral Raise": { icon: "🦾", sets: 3, reps: 15, rest: 45 },
    "Face Pull": { icon: "🔄", sets: 3, reps: 15, rest: 60 },
    "Hammer Curl": { icon: "💪", sets: 3, reps: 12, rest: 60 },
    "Bicep Curl": { icon: "💪", sets: 3, reps: 12, rest: 60 },
    "Tricep Extension": { icon: "💥", sets: 3, reps: 12, rest: 60 },
    "Skull Crusher": { icon: "💥", sets: 3, reps: 10, rest: 75 },
    "Leg Press": { icon: "🦵", sets: 4, reps: 12, rest: 75 },
    "Leg Extension": { icon: "🦵", sets: 3, reps: 15, rest: 60 },
    "Seated Leg Curl": { icon: "🦵", sets: 3, reps: 15, rest: 60 },
    "Lying Leg Curl": { icon: "🦵", sets: 3, reps: 15, rest: 60 },
    "Calf Raise Machine": { icon: "⬆️", sets: 4, reps: 18, rest: 45 },
    "Chest Press Machine": { icon: "🏋️", sets: 4, reps: 10, rest: 75 },
    "Incline Chest Press Machine": { icon: "🏋️", sets: 4, reps: 10, rest: 75 },
    "Pec Deck": { icon: "🔄", sets: 3, reps: 15, rest: 60 },
    "Cable Fly": { icon: "🔄", sets: 3, reps: 15, rest: 60 },
    "Lat Pulldown": { icon: "🔄", sets: 4, reps: 12, rest: 75 },
    "Seated Cable Row": { icon: "🔄", sets: 4, reps: 12, rest: 75 },
    "Assisted Pull-up Machine": { icon: "🤸", sets: 4, reps: 10, rest: 75 },
    "Assisted Dip Machine": { icon: "💥", sets: 4, reps: 10, rest: 75 },
    "Smith Machine Squat": { icon: "🦵", sets: 4, reps: 10, rest: 90 },
    "Smith Machine Bench Press": { icon: "🏋️", sets: 4, reps: 8, rest: 90 },
    "Hack Squat": { icon: "🦵", sets: 4, reps: 10, rest: 90 },
    "Hip Abductor Machine": { icon: "🦵", sets: 3, reps: 15, rest: 60 },
    "Hip Adductor Machine": { icon: "🦵", sets: 3, reps: 15, rest: 60 },
    "Glute Drive Machine": { icon: "🍑", sets: 4, reps: 12, rest: 75 },
    "Shoulder Press Machine": { icon: "🏋️", sets: 4, reps: 10, rest: 75 },
    "Cable Lateral Raise": { icon: "🦾", sets: 3, reps: 15, rest: 45 },
    "Triceps Pushdown": { icon: "💥", sets: 3, reps: 12, rest: 60 },
    "Cable Curl": { icon: "💪", sets: 3, reps: 12, rest: 60 },
    "Ab Crunch Machine": { icon: "🔥", sets: 3, reps: 15, rest: 45 },
    "Cable Crunch": { icon: "🔥", sets: 3, reps: 15, rest: 45 },
    "Ab Wheel Rollout": { icon: "🔥", sets: 3, reps: 12, rest: 45 },
    "Hanging Knee Raise": { icon: "🔥", sets: 3, reps: 15, rest: 45 },
    "Flutter Kicks": { icon: "🔥", sets: 3, reps: 25, rest: 30 },
    "Jump Rope": { icon: "⚡", sets: 5, reps: 60, rest: 30 },
    "Rowing Machine": { icon: "🚣", sets: 4, reps: 500, rest: 45 },
    "Bike Sprint": { icon: "🚴", sets: 8, reps: 30, rest: 30 },
    "Treadmill Run": { icon: "🏃", sets: 1, reps: 20, rest: 0 },
    "Stair Climber": { icon: "🪜", sets: 1, reps: 15, rest: 0 },
    "Elliptical Intervals": { icon: "⚡", sets: 6, reps: 60, rest: 30 },
  };

  const EXERCISE_LOOKUP = Object.freeze(
    EXERCISE_LIBRARY.reduce((lookup, group) => {
      group.exercises.forEach((name) => {
        lookup[name] = {
          name,
          category: group.label,
          ...CATEGORY_DEFAULTS[group.label],
          ...(EXERCISE_OVERRIDES[name] || {}),
        };
      });
      return lookup;
    }, {})
  );

  const EXERCISE_POOL = Array.from(
    new Set(EXERCISE_LIBRARY.flatMap((group) => group.exercises))
  );

  window.FITOPRO_DATA = Object.freeze({
    TAGLINES,
    DEFAULT_WORKOUTS,
    EXERCISE_LIBRARY,
    EXERCISE_LOOKUP,
    EXERCISE_POOL,
  });
})();
